### ISSUE TITLE
faucet not working

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#10]
I've tried funding my wallets several times but they aren't confirming or showing up in the block explorer.  

The Faucet says success after copy pasting my address.
![faucet](https://user-images.githubusercontent.com/33641483/46304255-ca417b00-c573-11e8-9be0-8b557a7e0933.JPG)

The block explorer says the same for every transaction.
![block explorer](https://user-images.githubusercontent.com/33641483/46304332-fb21b000-c573-11e8-83d2-087bad8e1c4d.JPG)

And this is where the node shows it's not been confirmed.
![node](https://user-images.githubusercontent.com/33641483/46304381-22787d00-c574-11e8-8d79-bea651da7b95.JPG)

The three wallets I was trying to fund are:
SamSept30
TEACJJxo4hz5goE3wXUpE1haVPQxpygkpg

SamSept30no2
TR3uSdwDVa9HpvXddX2pUJK5fBm5ZUt4C6

SamSept30no3
TKkm6t92guS27cEY3VcyQcxi9VASV2MFnG

**Comment by andrasfuchs** [comment]
I don't know what the exact problem was, but they all seem to have the 100 STRAT-TESTs on them now.

Next time if the faucet fails you could transfer the funds from one of your older wallets to the new ones. It's possible with the swagger API or using the standard Startis client (https://github.com/stratisproject/stratisX/releases). If you use the client, you need to make sure that you run it on the Stratis testnet and you also need to import your old private keys to be able to initiate the transaction.
