### ISSUE TITLE
rsaPrivateKeyHex

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#13]
On the decrypt-wanted-system-message section of the instructions I found I couldn't move forward because I didn't have a private key.  It looks like the response body didn't display it when I made this group on the 30th, unless I'm reading this wrong.

When I created my test group SamGroupSept30 it didn't display the encryptionPrivateKey in the response body.  This was what I got:

 {
      "network": "StratisTest",
      "address": "2N7uXzz7PCLZzaCAaE4gRUzUJFUVgX2ERdS",
      "publicName": "SamGroupSept30",
      "groupId": "cd4b434e8c107e6791d0dfe435dbf76697b972cce83d1419985dd26f6906ad98",
      "groupName": "SamGroupSept30",
      "validFrom": "2018-03-01T10:00:00.0000000-08:00",
      "validUntil": "2018-04-01T10:00:00.0000000-08:00",
      "scriptPubKey": "52210246b58b841406f99c83b31d61c0c87118fd37935b66778131631ad31d96945b052103d58dbc1711a58dd43054bc6f559483796c6cbcd3a3ef0d9154c5d9c2cc7f572c21032868c318b79df721a1771a7094447afd5ee0e9a5b71bd233f9a2d5ebfe2228ed53ae",
      "encryptionPublicKey": "010001,8b9251e2abdab73f9241bbbd39070a6f8e1766701ea7ca08fd0bda358522da2dd6ed15c50542477cdd9e156fb8781d8c7f8ec75aad19d33b4c1495fc051afe76d75f8a6c27b312683b0a63310f4d0a37a94cf7d2fd345c2d8a8cb0364ec312d913acdeaf5ab60b6cdbf64ac3d8783968c10c3676e7d69c7befa84cc97a9d0297a81ef85869ee863f47933db3ba3e44ee890bfa90db2f2e8757c95f4be48ff65a73da6f6d8fdd8eb09342258428704c3afe8d6b0bc6c6b6fda6178102d6914733bd8e32fc83f88933f86b1d87be5342ec4611f8ee694e482939af96b60f4ae8548e8e65fcdd6d0ad374fbe30041a610fc4ea30b814d631bb2780c5736ee036f18244cc5563413439e7899240a1350d0e9a4e9495706806b1fa42801fe193cb6cc1e7a631e4230e9c66295e38b963e1866e7288f6de41d72db464428a43b2619533eef62ec7742c43fee484a0a9e32bec2d77f0884f8a8e032fc1c4fef1ac5daa55b67c6634bb0b8a5445937fb623169640ea1f6e73b3004e7ce64482d30481ec7e7472cd0ee6b803dac57ffb71e74275497cdcb184784caf87ad16df0aab116ea6ab1fd7c3ce53cba828747563d749e4c932a6eea175d1cc64fa73d16d8e305272788c247fb192aa2e0d69e8bf5073c87d0554f2d47eeaaf7c6ebeef0988e8fcf888392a9302e836ac99b6fedbeea88e36170b841f1eedfa63588754dcbc8ce7f",
      "encryptionPrivateKey": "",
      "managerPasswordHash": "",
      "publicApiUrl": "http://node.aequitascoin.com:38221/"
    },

**Comment by andrasfuchs** [comment]
I have just tested the create-reviewer-address method with the following parameters:

```
{
  "rsaPassword": "WantedReviewersPassword2018October",
  "signaturePubKeys": [
    "03e803b1c7825f07754577688f81b5507883c0c69415fb3d51ca0a036e4a3f850e"
  ],
  "requeiredSignatureCount": 1,
  "publicName": "Reviewers' Test Group by Andras (2018-10)",
  "groupName": "The Wanted System",
  "publicApiUrl": "node.aequitascoin.com",
  "validFrom": "2018-03-01",
  "validUntil": "2018-11-01"
}

```
I got back this response:
```
{
  "network": "StratisTest",
  "address": "2MwwAteNpNfdsc32oo4BRCd7bMgEu25xEqo",
  "publicName": "Reviewers' Test Group by Andras (2018-10)",
  "groupId": "9b6248f11d150b5c9d8a42824499fd7ad8b1515064e226aa2b27b4206690f2a0",
  "groupName": "The Wanted System",
  "validFrom": "2018-03-01T00:00:00.0000000+00:00",
  "validUntil": "2018-11-01T00:00:00.0000000+00:00",
  "scriptPubKey": "512103e803b1c7825f07754577688f81b5507883c0c69415fb3d51ca0a036e4a3f850e51ae",
  "encryptionPublicKey": "010001,99da23451dc7a95e7fe31ff5f1151290a2a9d55fd85510fab94b1755ea45795eb223ea64208dbecb1d0e5c8051f39001dc125feee205dbac5e35f5a5b11c88f4eda4eeed0ce1a204bb93dfd938ceb0336cf471178b44321c218e73a356c39b80c9a60bab030695cb8df4ed5301d04ce7098dca0cdb1bea6e071c14ddd36ca0e1c419b097156e1ca9a1d4e6595e4e6b9f8da8e7f5a3caab974eb7eec3c6e9d014970bd3cbeea51794b59b1ac007db6d9c16ca22aad48da1933e12dd34bc07ab2b43fbf68ef83099ab1acaf8d1aec74be6b229286cb2a382ffeecc4c25567eb5c7ac5af1258df8c12660ccec63f3ba665ec91cd418205be9abee0ee341e30d5c8c025c0badbcf9bc007c626bcedc9e6fcf01d6c2863bb0b5759f8344edb4c46d67fd3c82b8062e1dcb237eb6a79850ec2e350a39205eaeca847e2e6689be6fa0890f99c8d413b4dca1872fa46b791303b25c325bcc4395f410d6bd5a5c0817a08e8611360977d05b0e2df041cdc389ee818d4c68bc5c8492887e9d7a4be67f24b71ff55135949abdb870bcf736e997e4871b5d0ab281df376f1b4c1a32203dceb46502f5b6043dd03e7c67edb04268af48c94a9813fea8823286226e420f3322ee7b63c7ee8bea1d77fefc9c817e5b7a65286217769b70ea82d0ba39d87f377dc20dcfc9633f07656c5153c596bbe83ebffc9672eeb00c08a7abbf42c53742e3f7",
  "encryptionPrivateKey": "27438a5c1879969efbd9036924701bc3abba0fd577d5af951963e83a65de0d77b3d9da47c0cc086cb4cdf1e74cf440a6f8a6f775df24c11a7f283f682d71fc71abf87522a68fb6aaa083c32fe2b3ece74fe176cea6ec75c761c85eb45a3cd3967f7a87489e7674d9d3019ab7a9749e2b93b17c7a56afc7c8551dfa4153d5e292c9fb9471f4ce9fb8f4876140bb976872d5afe75c2a4fd65e27a25e82fccbb1c2f6749fc7b2eb83b2b99482a809bb2e044aa289a247024c2c168468b4bbc420c51ffa6a5bca103a7256ecbacf0916b10d171ea793e714cb9f7b2131cc77ed621d330f1047b267f3694bc9bcb9233bf565c45284ece300d9ee7837792a0b1977a5,6aac7f92eda5adc2cb666d953fdd05120c0cc3b572b1c746a155297be180edd38ed8e1bd3873abb7c513486bac8bda76181631f8a8337556fe01bdbdff7e98274b5d575c844b89020bdb42574da928d88317613ed1836c12f0f494ddec7175130c1cc4a07316a929f70aca6eb3b38b7fa01a7a35d20be5e7bde0da0296c30b997698115341e128e295f34e57068ec39ee5c1dfc7f8fc9bf2e905851a81e835d4026fc9175af30fcba679544498ab019e56cd101cf18a5391cf0a89745f6b4d2ccedb7a2a71881d17b6a03a75b06366c1303d08d43c343f4b0bedbbef9c1f1185012896fc9314a63521b90310bf7041dfb37881cd7ef92a9497671d376c832ba1,139ea74fc997ec27e26c2ee7b8ba44b7501f13585928a3f52d4affab53a84f6d7d8f29f561d761a4da4c3a0c9d26cfcf04e70cf7d438060709ae9ce867d92937fed44129d6b2316ca4151bff4208cd9c8940f4e91937f5a1f3bf8c4ca0a46a40b6b6679783d7c3a385335e4e6f1546b151dd148ea6247db5514fc9f36de254f3e583972af52f291592cf291eed7157b52da6040aa5bc133cc4eb9cd5b7989a91fd9f22ffc72ba381b1d51948b2d7cf37100aeff7d40a49b812baea1daefad55fbb98369d8dd5f8cac2ac6ea5a2c1c492a356af52894763cdca80a01744dbfcc77d59cd95c9f0968513e41e2332f22adadc8fc2165f8e091305553db2e9c70aed973d9424bc84621902435d884b9a3cfcaa22878db40b497d88b10d5bc96c617eced51033d775d105080d7830f94b0733b2d224e7db5cee2064c04657171e38f0c08ab748b43a6f33ec3d6bc9672ab522101f271ceddb32e4f0b6b810f25d00822066c1c4373d703f70795165de207a2225957caf35d31620c532446f9c5cd969b7f7735ad20db871d2045381e4d1809e4f041a5c4adfad4ea5080cf59836b622dfa82eae756aabf2a6013d3022ac54ef5da4b45234c240c2fb4dec3743868c3a13581678bb30e63ddb36f16db0b0661892c7b0c5cedb9e4105e0c427d04bb21bd21ca6db165a6b3241fdf4ed93ab6ff26789e019fb45694915095b3087ca94b1,99da23451dc7a95e7fe31ff5f1151290a2a9d55fd85510fab94b1755ea45795eb223ea64208dbecb1d0e5c8051f39001dc125feee205dbac5e35f5a5b11c88f4eda4eeed0ce1a204bb93dfd938ceb0336cf471178b44321c218e73a356c39b80c9a60bab030695cb8df4ed5301d04ce7098dca0cdb1bea6e071c14ddd36ca0e1c419b097156e1ca9a1d4e6595e4e6b9f8da8e7f5a3caab974eb7eec3c6e9d014970bd3cbeea51794b59b1ac007db6d9c16ca22aad48da1933e12dd34bc07ab2b43fbf68ef83099ab1acaf8d1aec74be6b229286cb2a382ffeecc4c25567eb5c7ac5af1258df8c12660ccec63f3ba665ec91cd418205be9abee0ee341e30d5c8c025c0badbcf9bc007c626bcedc9e6fcf01d6c2863bb0b5759f8344edb4c46d67fd3c82b8062e1dcb237eb6a79850ec2e350a39205eaeca847e2e6689be6fa0890f99c8d413b4dca1872fa46b791303b25c325bcc4395f410d6bd5a5c0817a08e8611360977d05b0e2df041cdc389ee818d4c68bc5c8492887e9d7a4be67f24b71ff55135949abdb870bcf736e997e4871b5d0ab281df376f1b4c1a32203dceb46502f5b6043dd03e7c67edb04268af48c94a9813fea8823286226e420f3322ee7b63c7ee8bea1d77fefc9c817e5b7a65286217769b70ea82d0ba39d87f377dc20dcfc9633f07656c5153c596bbe83ebffc9672eeb00c08a7abbf42c53742e3f7,cc845de9838375fb15eef9a7b1680e669e164a756ef3e6fd5fef1ac840a1365c666a55681d604390c52bccd55f025a28f6b8812d4351ad0d64b09421a13aad586f377cb4c09b8dc812329db817d79fde13f49449b08c916f0adc28ca04fd1109618fe7f947cdeefefad202dfd0b869ce4f9e03bd7d94c889a467ffa90a712cfac30c9fa1211862cb4ebf74d5012ed6a929edca73085795d4e7f6087de3e51cfca07c28c7f070728e49f6e3babf9125a15c78b379132d99aa313fab380b3fb20ebf00fbc5a79d73a945332fba69ac9f6e528533dab2a81e097f2df61acfa754a745b669dbacd0f4825d3fb1ed8644c8bbb61b73d74e34eb847fe5a8b41ce1d227,010001,c094c8aa94ccecf2ef11e067ac85584c4825af165f23b5fc4f1f173c8a7a552275e968e09b26356bf15a7cb30ab39796a2326bffe7097245e4f43179838d22a36ec3306752a299594c44deea8c47dcebd856cc3d74c0fb182ad0eb7f197b3c8d3778280914b65d836854f8ea90212aafc9cca65f2ccac1e5e0c733e99bc2ce4255003d3c01aacdbef9082b0fc2a91f06b585d08a0df052b3b0cba5adc46a82c5e1321463605c5f2a00da677ad6679f985e119f4a20b00d8332e747836250e7795d45699c0785749fbd25a6a6b336406e4912ebbddc26b9ccc4e5628db030d6dc02f91aadbf1a3a6e51fcad523ab521b1a5ef159439322db584642b9955f411b1,1b7bc5e8eb4e4390766e1ea4f044931832f549d22a676c7a1a531294a48e09ac458054767fb85ed5570d8491033e8a6978e152f5fe2cc6a1cace8d59788f56276d236bb4fee44cde98c95c7043902ef5d8b9259673d758f8c2235637c405fef0840dfd749d503aca5d7ce550c3311fcb72dfd44674de9d2717eee5f44759bfaf18e9249bc05fa410ea8f107f2c441153ac852bd1b3ed0ea72bd64ab0a25d0bc3a540e0de5f7669793d23bc709fbd55bb7685c03ac13edfdc05fe8bf3253b8248d0a368418e08b787375bd0c8bccfe45f8f372f766c3a8522dceb49e698845febc1f17cc7cb9bc23e91f86b726fdbd8d3df3fedde05bf142ac6b05e281ae7186f",
  "managerPasswordHash": "4814faeb63b336924f4898e3c691d8dfdf325972f1f78803a8f467479a4fb86a6eea90e9fc18f8239b2dce383877a17dfb1ffd01e71dbce1c6b8d132e93f471e",
  "publicApiUrl": "http://node.aequitascoin.com:38221/"
}
```

I think it works now, but I can imagine that it had a bug in the past. Could you try to create a new reviewer address and see if that returns the private key?


I also extracted the private key of SamGroupSept30 from the node, in case you need it:

`"e73aa8d564b547835fda4f7be69ba7f32a6dd2da0a1b548eb0eda8bfcdfbe6ec08145ecd028edc1d39b399ae47cfd645d73b1ba7dd06244db60d73d67ba3b4466639cf2995aa0bc8373fa4eec80e54a6d9dd52b37014e9d4cfd6552b7ff7c16014d516ca74938e6436ab97bd23d3abe4294017ccd297b76fe89e1a809a4d32cd9c4e553aa48a5a06143d562f182bac50e13a2b6ba93b319f5791a865cd3be08b9d3bdd7122c50000caa91ad93f008c28f173d78aefce438714348a3620608ad8dc71a9214068677e624455a02f281d5a8fe649848e293b0c90bbad43843042e6a23c7ca4cb35b9888cd6fcfd1513f68eb44109b1f76d88ab662b07c9d9b7ebfb,0e8929740ce7e1257fd101f9fbe61b055689f40fbdff5add89467ecebf3c2f3e54e05381052641ab309bd48d58e70179cfd62d1820574cccca4180221bcd732151bacc6dfc313d2fd8e48600ac3eddc757a5a70d52bb30ba808b2b629de28da69349fd0472ee97169b130380958d981319b5c4155dea02a7f5c9b2a4ae5b1047a735d736ff9224fdc5ae870ce91f960feb07960899a95914497d771b12d24f831a35bcc3d46f3e4c2f8162112fc1170b8365a51fc0a96d3be997af36d972dd29847017f37c267b37fa90eeaa55b1812d4dc16e1b004ed0494c4ac62ade6109df2cb4b0a2efa85c362fbe66c7dde2c43c15627f88444313dc9e5e5fd3887079a1,047ba1a7af2f6a3d5f7c3f0477e572ff5c4802214dcac3e18007366e0ba5afee52fdf07a108e2d6fa44aa4939f10349ac3aa195b1f3e3a1ba878eccc5879a27cbcb433e4ff6d7004eb088d611105bf73443bd5a5f03e134bdf2c5fa88ee51320e7d1e0a12f3fb3a43e786db456aa9de57075ecf5eac268ea4e2b50b413fd210d2ff836afd84f31feac54dd617d74ec8fe0d502aa4e6ff8859e5b38755e95052ba896f687455caf6d9a7d40693b47481b88fb8fd9a3fbd3fad7afdf93f0c25fd018a18d9fb0b975e6b66ef256ded51bcc2cfffcc7e398011759e3faea44197ad6e4714c734fc565d89ee44c4940d28daf1cf37db61c7f376f870d966b8c3f8dfce2fbd93c20a585bf4a712df21f5871c1f2b4e11b0e47415e7363adccf79aa0ff98a3c4f76598b0d8844aec7e3c3522fbc4f00e50f306ddf6617c9c06d4c2b1163440a30472ab86311aa215810de1ec3945e14f94ac7c13b2def9267b676465c13bd41f9a00acaf012bc12cdd0c68aaeef421616ec455ebdf82617925fb2c1445d3fbe56143ee4bd9a0bfaaa73381387b0a776b332cb36b9b95ac6c4689724d89a8d5740e48fa2337f8ba05f13ad7b0be87bb23e55da4258e3e3353c9ac634cad5cef882cceecf469b3e918eda06c2a712d6be32cf539402c841b8642eb76b08714f9c1a3a2f1655bcc6e376667d5f4553540b91be547466ce4c2a58aca666371,8b9251e2abdab73f9241bbbd39070a6f8e1766701ea7ca08fd0bda358522da2dd6ed15c50542477cdd9e156fb8781d8c7f8ec75aad19d33b4c1495fc051afe76d75f8a6c27b312683b0a63310f4d0a37a94cf7d2fd345c2d8a8cb0364ec312d913acdeaf5ab60b6cdbf64ac3d8783968c10c3676e7d69c7befa84cc97a9d0297a81ef85869ee863f47933db3ba3e44ee890bfa90db2f2e8757c95f4be48ff65a73da6f6d8fdd8eb09342258428704c3afe8d6b0bc6c6b6fda6178102d6914733bd8e32fc83f88933f86b1d87be5342ec4611f8ee694e482939af96b60f4ae8548e8e65fcdd6d0ad374fbe30041a610fc4ea30b814d631bb2780c5736ee036f18244cc5563413439e7899240a1350d0e9a4e9495706806b1fa42801fe193cb6cc1e7a631e4230e9c66295e38b963e1866e7288f6de41d72db464428a43b2619533eef62ec7742c43fee484a0a9e32bec2d77f0884f8a8e032fc1c4fef1ac5daa55b67c6634bb0b8a5445937fb623169640ea1f6e73b3004e7ce64482d30481ec7e7472cd0ee6b803dac57ffb71e74275497cdcb184784caf87ad16df0aab116ea6ab1fd7c3ce53cba828747563d749e4c932a6eea175d1cc64fa73d16d8e305272788c247fb192aa2e0d69e8bf5073c87d0554f2d47eeaaf7c6ebeef0988e8fcf888392a9302e836ac99b6fedbeea88e36170b841f1eedfa63588754dcbc8ce7f,f3cb905b5231f1050ae241fec8040bf04f687eb76eb08537545c2da3808e8d5ecea44c3287ef06c459f79ed8445bddf05d3efee34d1a167626f2f4d389f940eb7ceb0e1853bc374778d902dd35058ad16299dc327890c7c4f6e831fd43044d14a3756b8f6a361676107f6f760ff98a840d14d0a1068be5758335dca22c15525e5df12bed70f401560e784b455c5194a6755d3fbb8dbfb8f12eba68fa42ee9b569f74f0425b8ff8f91897492ebb4ea38484b781b4c92ae204d9b79d90250f8d61694858f0212f6a6114608520a8984d9a5e9ad1b312ea4e04fb81fba7e31ed0945a1bc75192edb682da841205d0c82c31a5baf52f56949e990ff1c21627c45ae7,010001,928f0b63f8e8733704d32c1230d727ad82e2f53255fafe2506eed4e225ecb86b49d52a1da499655aac9fa1d69fea5a75934c4907eef697b68cc5a5b70ea238fafe1d3acaef1ce2449c73464f2c400a53b586039542580aefd2da301e9ccbfe7814d1391ffa72c47f6051dd2b0cb059825ac6ba04ce0928e14c280820ceae2f0daf8e82a1e6d6bf3f97e0fe670978ccc7cd40ca4966a25f600ac818e98c4384b3fa0beebb849c62c10e3d807ebb8f786215c93277a45beb6a4ad09cd9be880efb2de83a1d76b432fb581991da0c1fc73d3d8c34298714f9dc42f4e96110b20741528b79728ac3800583185c3fd44eda4d929cc9716b6a57e4fdc13a859a6354a9,c798c2f9b12bdf7497601ab188288bc78a6d61662233882cf84163025b152509a8113147055daad5028b3994fedc49772ab0e2f93271bcd2633b1f6fbf77d0189ce6a06b114e724bd7d4f3e26e6cbf274ad0046781275a0323d6ff2b2101aa11503d0b34d83ef772cc6a8eb499f871e4a888bf166b857b8916adaa5fc4f80b24c1f792dfcec8532412e87c365379d7dd233741343983f23edc752b26e90840460e472fe0cb2896241fa85d9cbe9277aaad6500db168c3e86223399d57a872822d6d5f4f0b562d595f9653f5dd29630b4f98e48ffc1f9d8da1971824782a63a158167a72baa701ad4f0841f166a6a853433433f466a88cbaa0391ea13baa30011",`
