### ISSUE TITLE
list-spendable-transaction-outs error

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#14]
I used this code:
{
  "address": "2MtPTdedHzF6JsxKC3zLhfRaRY4rXUj8PzW",
}
and I'm getting an error.  

{
  "errors": [
    {
      "status": 400,
      "message": "The address you requested is not in this wallet.",
      "description": "System.Exception: The address you requested is not in this wallet.\n   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.ListSpendableTransactionOuts(ListSpendableTransactionOutsRequest request) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\Controllers\\WalletController.Messaging.cs:line 784"
    }
  ]
}

but when i go back to make sure its there using: 
/api/Wallet/list-reviewer-addresses
with:
{
  "groupId": "",
  "publicNameFragment": "",
  "validAtBlockHeight": 0
}

I can see it in the response body:

{
      "network": "StratisTest",
      "address": "2MtPTdedHzF6JsxKC3zLhfRaRY4rXUj8PzW",
      "publicName": "samoct25",
      "groupId": "8769fd826dbde432822851f23a3324a658e4366c6fdd7de350393f0686f2580f",
      "groupName": "samoct25",
      "validFrom": "2018-03-01T10:00:00.0000000-08:00",
      "validUntil": "2018-04-01T10:00:00.0000000-08:00",
      "scriptPubKey": "5221023b2f06f9b861d41f3922a7437fd5c941076d9784cd308a0ed35bf1eef13c9b5b2102b280fa097fe86feb4af189fac4dbbed8026f14581facd3c85bb7c1fe3a25895f21032080b5490089003f9b0c30e76e851b8927684164727f394a48266a7768f53b3f53ae",
      "encryptionPublicKey": "010001,ce9585cdc04568b3dee3c18626062c64bad2d8949f35c95d4e4d47f492d46948a54213d1bd18ac57b81a7c18266c0d07b4110b629ae6cc69c292af7b6f385cd059eab3f2e227d7fc37d860d1192fd7b0fd7aaa7b1c334f821f5cb612b5bdbf611a939801a41a68976c674f52f51940bf744dc67f15d837f4dd35f83ac4f88636aeb4c582ff658c0832af1d664e2898de2969522e06d4066b22928c4ddfd1d8901e9e52ff19f271101812a3bf65a36c72e744181a37fa0f9a4a631a4e431d6e1cc71f1a88084831d70f3159dca8a1d38e4dc374a7d7dcfa294fc5a4b5ac0583ceae87144ece1f7798d632e979d3bd12f7d42063e14108828b8a7d8cddae45ca0fb2190d982918112cadf59ec2da0b9983450c530ae614819d2b21920cb6ba75b08efeaa89e82558aaf6785a482e8c5113d655ca609c81794971e6e797e22445b04b88c72d3e48b80f5dc25765da184663e4720061a47b30592bc49529e669395ceb6c74fd0950c72b24e1f849489a95f60e67a052f5835bedf1468f6f1b1840240f32e0e83ff134cdeca51c30edf882b76d4b5c0cf4c8bf6e47f7b69b3533bceddb79e9298e8aa35ae327f1b023481043fd7d5f8937614a043c0d2c82ae26cd469499203bf71fc574076ea240cacd0d37f66040139215194748fd0a5e68b246cc3f4dd262174b7f069f526e9ae278819a4866b8cb29a3ec944567724c3015c767",
      "encryptionPrivateKey": "",
      "managerPasswordHash": "",
      "publicApiUrl": "http://node.aequitascoin.com:38221/"
    }

So it's showing up in the list, but its saying the wallet doesn't exist.  I also tried running it on a standard wallet just to see what I would get and I got an error on that too.

**Comment by andrasfuchs** [comment]
I must admit it's a little bit confusing: there are two methods called "list-spendable-transaction-outs"
* one of them is the **Wallet**'s 
* the other one is the **WatchOnlyWallet**'s
You probably used the Wallet's not the WatchOnlyWallet's. (As I just did a few minutes ago.)

If you open [](http://node.aequitascoin.com:38221/swagger/index.html) as you normally do, look further down in the list for the second "list-spendable-transaction-outs" which is part of the WatchOnlyWallet.

Calling that with the parameters you had, I got the following (good) response:
```
{
  "network": "StratisTest",
  "spendableTransactionOuts": [
    {
      "address": "2MtPTdedHzF6JsxKC3zLhfRaRY4rXUj8PzW",
      "transactionHash": "dbb931012f3ceb69f0c92e499f09e2f9bb18f014393368ae6bb46c67df0ea168",
      "index": 1,
      "amount": 25000000,
      "scriptPubKey": "a9140c86d7d62336e4838ea13346ccf6d21806a809c087"
    }
  ]
}
```
