### ISSUE TITLE
Code 400 Error on /api/Wallet/build-wanted-system-message

### ISSUE THREAD

**Issue by rule144** [AequitasCoinProject/AequitasFullNode#15]
While trying to send a message in 
/api/Wallet/build-wanted-system-message

I got a 400 error when entering the following input data:

{
  "walletName": "string",
  "walletPassword": "password",
  "accountName": "account 1",
  "payerAddress": "TC7R8zPJepEDgB7vvgpzdKekTTrK3i2oi1",
  "destinationAddress": "2N99n1ho9WvEXXoQ416Ba121Q7B9Y983XMk",
  "message": "Hello world btc is crashing!",
  "encryptMessage": true
}

The error returned is as follows:

{
  "errors": [
    {
      "status": 400,
      "message": "The reviewers' address '2N99n1ho9WvEXXoQ416Ba121Q7B9Y983XMk' was recognized, but its private key information was not received from the 'http://node.aequitascoin.com:38221/' address. This is usually means that the current, requesting node has no access rights to it, so: (A) you must use a different address from your local node OR (B) call this method on the node where the address was originally created on.",
      "description": "System.Exception: The reviewers' address '2N99n1ho9WvEXXoQ416Ba121Q7B9Y983XMk' was recognized, but its private key information was not received from the 'http://node.aequitascoin.com:38221/' address. This is usually means that the current, requesting node has no access rights to it, so: (A) you must use a different address from your local node OR (B) call this method on the node where the address was originally created on.\n   at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.AddMessage(TransactionBuildContext context) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\WalletTransactionHandler.Messaging.cs:line 42\n   at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.BuildWantedSystemMessage(TransactionBuildContext context) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\WalletTransactionHandler.Messaging.cs:line 57\n   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.BuildWantedSystemMessage(BuildWantedSystemMessageRequest request) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\Controllers\\WalletController.Messaging.cs:line 143"
    }
  ]
}

**Comment by andrasfuchs** [comment]
Hmmm, strange.

I tried to reproduce the error, but when I called the **/api/Wallet/build-wanted-system-message** on **http://node.aequitascoin.com:38221/swagger/index.html** with these parameters:

```
{
  "walletName": "string",
  "walletPassword": "password",
  "accountName": "account 1",
  "payerAddress": "TC7R8zPJepEDgB7vvgpzdKekTTrK3i2oi1",
  "destinationAddress": "2N99n1ho9WvEXXoQ416Ba121Q7B9Y983XMk",
  "message": "Hello world btc is crashing!",
  "encryptMessage": true
}
```

I got back the proper response without having an error:

```
{
  "transactionId": "f3baa1c8b55843bfb5db3aaed61b4ef33464084a424719bd15bb549c123c2b40",
  "hex": "01000000662df55b01a9a037da7851cdd2b88f1bd272cf4425438bc8d296f6fce2db04624ee3451579010000006a47304402205627bd7ad39b19a44524eec58d4453675e0f65e1777c9c2d4727a3774d55b58402204a371e0f7069da9ffedca77eefa58d00f8166eaf1f0cb8814e8d6a085a948a13012103b152a99403f3069577fd7c19447a86ee8cc34b76a8abcc28c8ac040a01dc87d2ffffffff0304430095000000001976a914045266bccc29bd1722e09dd735cd72c67579faee88acc468000000000000fddf0261616a4dd902545753010100010002850047005cb182721c7c95ec91d6114c8c5feab6331f32769c5d0932b2b1a80443679e0fca21b5378d2620b0defcecdb32fcbaa1c10aeab73566904a77fdac04e0b468c20b63acde01250268699b001c24148fed04d502dcad0155ef00e92fbef8eade9cacb9fdbdd180cd38a458412abd707848ce7e8008eb7788fcad8c243a5c167d791a8803a11cc4a0d62e1811cb9b45f10262dd388d29db39effc0015ec74af7dd6595c5194395f9d4cdd4e2133cc519b031596bd0a01c452716009319efb79edb7f324732319d15fcaa8fec7a98e8f2932607c460f3262868d57cee427545f8d5ea2b8013a089c036c767330ff09b7e5c596e82f0281fd8c9f9c290674ea8844932f6bcee1753ba69dc147004b6e12c72b238607b9b4ca5f1fca9b2cd14c4aa0cf7a8bf4ac8ea20d5095c456899076ce42447f83453a46538ac82f022c415bfbf6257a2f4436787ffed7059a09a8fb284e59482fd8111a16552068d8cab6f10ffadce660f335a3c8df55d943900bc43a08cde8dd4c56174552f8b69ef96731425dac978e107522c9ff1f8e29af226a608a6997cb69f785d78e8a7111e3bd319ef367bac25614eb097ff034c199b8d4f31713f5a4319d20ac52b3385b73ca7032efef8cbab5af30a1a3fbc0b5a8a0f8aaa5b6ec3b7103720ef4792c63ed645920bf2ae06ade877f0451a520968d048b16330d79db50b287599b24e6c09e80f790021f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b2523234d43732d437b4503034b03230b602321c7d9574948a5293330b3253f34a1c53528a528b8b812a8dfc2c2df30c33f22dc3cb5c2322f2034d0ccd9c120d8d0c03cd9d2c232d2d8c237cb3c11a0b722a43f2e1daf24a737240a2e58945292882b500dcb3bf108b0000001f8b0800000000000003013000cfff8caab1f4689d6ed7b885af136cdc2875a441f50afe9ae55bff214f46a33be323b5f483dd3fc119cf7cfe74d65ec56172ce6dac7230000000c468000000000000fddf0261616a4dd902545753010100010002850047001ae0bd36132d6e0fdb92b96476c6cc08871b458625b33c45a4bdbdf1686009d0539a432c2338d11a80f0dbbf2f4d24fa4c4654de4815e3903cfba24459e06220689204a53cd22ceed987765e3d6ff6f960ddcc1a417df0784b4a4128a56020fb37c6c85e4cddc2fd84fff6b93f2f566d73558b11e59a0abd8f2458baf8b3957f0c602e97f4730f898dd7a8780fd2c142eeacddd54acbda6d90e24fcf4f5ca2d22519df95988902b41ebab1bf2ae910d45cf68c81d0d9388f33c2f2f8adf88cce7283ef1a92b1e253c7fa27f49760d4ffb38c437ff297d84a136821908eec7e14dcdb5b75f901893dad83238315a0bfb85d409db1482568e0823a05245c11b02e2bec0f52f0b167815fcaea3185ffa443f0021f95aeadbb2ac72735ecd1b700d9b632bf4826488627bcd938c5cab17282f38b7b8bfc45c2b44fa7741d5b3f24228d56b4e6f5d9234e1f0c6f27cb55f12a802082eacad6a521f5f3a7ea181b4c40fab047a13398ec83d7066879b0b9ae73f634d7a8fdaecefbd7f665470416f8a02a250b2adae6f04823e6811e199c47f0c0ad88cfd56cf5727fea96e1be3793d99f95a51f8c7b3da7625f9467db93df4b92db8d37b562f22585015527e79718ca5004ff7011bdc32e04f35c67b3612054a46805f5fa7b75d8faa3aef9987393a140b0e33413d8780baf74292188e642866932ca5b93ac16d78392887d68fa229a1f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b2523234d43732d437b4503034b03230b602321c7d9574948a5293330b3253f34a1c53528a528b8b812a8dfc2c2df30c33f22dc3cb5c2322f2034d0ccd9c120d8d0c03cd9d2c232d2d8c237cb3c11a0b722a43f2e1daf24a737240a2e58945292882b500dcb3bf108b0000001f8b0800000000000003013000cfff17efb3cdbe28f6296da787d4f66ea39776e2315d804c6f2dc368fdf2ba8450b09d2ecf69d11a827dc69babc903803231f21a27eb3000000000000000",
  "fee": 11760
}
```


Could you try it again? Did you use the **http://node.aequitascoin.com:38221/swagger/index.html** URL to call the API or you tried it on a locally running node?

The error you got _might_ be connected to the send request exception you had a screencap of earlier, but I can't tell for sure at this point.
