### ISSUE TITLE
Code 500 on build transaction

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#3]
I get:  Code 500 Undocumented Error Internal Server Error while trying to build a transaction. 
 
My JSON Segment:
{
  "feeAmount": "0.001",
  "password": "testnet01",
  "opReturnData": "string",
  "walletName": "samtestnet01",
  "accountName": "account 1",
  "destinationAddress": "2N4vnuoFAY1hUMXAN1gihAJ4qzmwqDgxAeU",
  "amount": "0.25",
  "feeType": "low",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}
 The "opReturnData": "string",  is not on the TN documentation.  I tried changing it to 0, blank, 1, and deleting the field and I get the same Code 500 when I execute.

**Comment by andrasfuchs** [comment]
I can confirm that calling the /api/Wallet/build-transaction method with the parameters mentioned above throws an internal server exception.

The detailed error message is the following:
_fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLGNQ9G6MRIQ", Request id "0HLGNQ9G6MRIQ:00000003": An unhandled exception was thrown by the application.
System.Exception: The 'BTC' money unit is unknown among the networks.
   at NBitcoin.Network.MoneyUnit(String moneyUnitName) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\NBitcoin\Network.cs:line 836
   at NBitcoin.Money.TryParseBTC(String bitcoin, Money& nRet) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\NBitcoin\Money.cs:line 286
   at Stratis.Bitcoin.Utilities.ValidationAttributes.MoneyFormatAttribute.IsValid(Object value) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\St                                                                     ratis.Bitcoin\Utilities\ValidationAttributes\MoneyFormatAttribute.cs:line 38_
...

**Comment by andrasfuchs** [comment]
There was a problem with the money unit parser. 

From now on we must specify the feeAmount and amount values in the smallest atomic units (like Satoshis in the case of Bitcoin).
opReturnData can be ignored for now, but if a method needs it to run, please specify an empty string (like ""). 

According to these changes the parameters should look like this:
_{
"feeAmount": "100000",
"password": "testnet01",
"opReturnData": "",
"walletName": "samtestnet01",
"accountName": "account 1",
"destinationAddress": "2N4vnuoFAY1hUMXAN1gihAJ4qzmwqDgxAeU",
"amount": "25000000",
"feeType": "low",
"allowUnconfirmed": true,
"shuffleOutputs": true
}_
