### ISSUE TITLE
deserialize-transaction unexpected response 

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#5]
#4 Verify the message transaction
I did not get the expected response from /api/Wallet/deserialize-transaction.  

The code I used:
{
  "hex": "010000001a7fa65b0131de8647b6354173a955e288284493392e97d56c158827f484f1b26103fa82df010000006a4730440220766189694d709f703bc12bb903272e093688845d07ed1ecf49ec8f7101481e450220271333e0d6c8800f5392cb7fbb68cd73396043d92e673470ae565cef3627112b012102b650eaca37d3dc997156d344b225dbb178c8b2245cad583b45d0983baa663c0bffffffff0308358c52020000001976a914aabd6b850032be4e2e8f776d19e6db8d9da7a17388ac2229000000000000c261616a4cbd54575301010000000085002b001f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b252b2d43732d237b45030b53231b232b15408f055d2512a4a4dce2cc84ccd2b714c49294a2d2e06aa33f23376718a727135cb2d4809284a2d08c94f090a730a49adf431c9b5304bb348cb32076b2cc8a90cc9876bcb2bcdc90189962716a5a008d602000b729af3890000001f8b08000000000000030b4ecc55284eac2cb6525008c95728c94855c8cdcfcf5304000cdb0b44170000002229000000000000c261616a4cbd54575301010000000085002b001f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b252b2d43732d237b45030b53231b232355008f055d2512a4a4dce2cc84ccd2b714c49294a2d2e06aa33f23376718a727135cb2d4809284a2d08c94f090a730a49adf431c9b5304bb348cb32076b2cc8a90cc9876bcb2bcdc90189962716a5a008d60200642a77f6890000001f8b08000000000000030b4ecc55284eac2cb6525008c95728c94855c8cdcfcf5304000cdb0b441700000000000000"
}

My response body:
NBitcoin.PosTransaction

**Comment by andrasfuchs** [comment]
There was a missing parameter for the deserializer. This new parameter was introduced by the Stratis team, not so long ago.
I added the parameter, the deserialization of the hex above should look like this now:

_{
  "hash": "ac9c6a09e79a41768c08a523438adccc0188763457a6f2a24ebed0b403926c09",
  "ver": 1,
  "vin_sz": 1,
  "vout_sz": 3,
  "lock_time": 0,
  "size": 601,
  "in": [
    {
      "prev_out": {
        "hash": "df82fa0361b2f184f42788156cd5972e3993442888e255a9734135b64786de31",
        "n": 1
      },
      "scriptSig": "30440220766189694d709f703bc12bb903272e093688845d07ed1ecf49ec8f7101481e450220271333e0d6c8800f5392cb7fbb68cd73396043d92e673470ae565cef3627112b01 02b650eaca37d3dc997156d344b225dbb178c8b2245cad583b45d0983baa663c0b"
    }
  ],
  "out": [
    {
      "value": "99.74854920",
      "scriptPubKey": "OP_DUP OP_HASH160 aabd6b850032be4e2e8f776d19e6db8d9da7a173 OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.00010530",
      "scriptPubKey": "OP_NOP OP_NOP OP_RETURN 54575301010000000085002b001f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b252b2d43732d237b45030b53231b232b15408f055d2512a4a4dce2cc84ccd2b714c49294a2d2e06aa33f23376718a727135cb2d4809284a2d08c94f090a730a49adf431c9b5304bb348cb32076b2cc8a90cc9876bcb2bcdc90189962716a5a008d602000b729af3890000001f8b08000000000000030b4ecc55284eac2cb6525008c95728c94855c8cdcfcf5304000cdb0b4417000000"
    },
    {
      "value": "0.00010530",
      "scriptPubKey": "OP_NOP OP_NOP OP_RETURN 54575301010000000085002b001f8b0800000000000003ab564a2e4a4d2cc9cccf0bc9cc4d55b252b2d43732d237b45030b53231b232355008f055d2512a4a4dce2cc84ccd2b714c49294a2d2e06aa33f23376718a727135cb2d4809284a2d08c94f090a730a49adf431c9b5304bb348cb32076b2cc8a90cc9876bcb2bcdc90189962716a5a008d60200642a77f6890000001f8b08000000000000030b4ecc55284eac2cb6525008c95728c94855c8cdcfcf5304000cdb0b4417000000"
    }
  ]
}_
