### ISSUE TITLE
unusedadress

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#8]
this is supposed to provide a block of addresses according to the instructions, however the response body is only providing one.  

my input:
WalletName:  SamSept30no3
AccountName:  account 2

Response body:
"TKkm6t92guS27cEY3VcyQcxi9VASV2MFnG"

**Comment by andrasfuchs** [comment]
Do you get only one address when you try to call the /api/Wallet/unusedaddress**es** (plural) as well? 
It should return a few.

**Comment by ghost** [comment]
It's working, sorry user error.
