### ISSUE TITLE
create-reviewer-address

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#9]
/api/Wallet/create-reviewer-address
returns a 400 undocumented bad request error

My input:
{
  "rsaPassword": "password",
  "signaturePubKeys": [
"0246b58b841406f99c83b31d61c0c87118fd37935b66778131631ad31d96945b05",
"03d58dbc1711a58dd43054bc6f559483796c6cbcd3a3ef0d9154c5d9c2cc7f572c",
"032868c318b79df721a1771a7094447afd5ee0e9a5b71bd233f9a2d5ebfe2228ed"
  ],
  "requeiredSignatureCount": 2,
  "publicName": "SamGroupSept30",
  "groupName": "SamGroupSept30",
  "publicApiUrl": "node.thewantedsystem.com",
  "validFrom": "2018-03-01 10:00 -08:00",
  "validUntil": "2018-04-01 10:00 -08:00"
}

Response body:

{
  "errors": [
    {
      "status": 400,
      "message": "The API request 'http://node.thewantedsystem.com:38221/api/WatchOnlyWallet/watch?address=2N7uXzz7PCLZzaCAaE4gRUzUJFUVgX2ERdS' returned an error 'The operation was canceled.'.",
      "description": "System.Exception: The API request 'http://node.thewantedsystem.com:38221/api/WatchOnlyWallet/watch?address=2N7uXzz7PCLZzaCAaE4gRUzUJFUVgX2ERdS' returned an error 'The operation was canceled.'.\n   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.CreateReviewerAddressAsync(CreateReviewerAddressRequest request) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\Controllers\\WalletController.Messaging.cs:line 413"
    }
  ]
}

**Comment by andrasfuchs** [comment]
As I can see it in the request, the publicApiUrl is not valid any more. It should be our new domain name: node.aequitascoin.com.

After I replaced that URL and used the your parameters it created the group successfully. 
Let me know if it doesn't for you.

**Comment by ghost** [comment]
Ty, it's working.  I was working from an older set of instructions and didn't notice.
